### ISSUE TITLE
create_objective_function with Abs fails

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/opty#119]
```python
obj_func = sym.Integral(sym.Abs(T(t)*omega(t)), t)
````

I guess there is a derivative of one of the variables:

```
Traceback (most recent call last):
  File "/home/moorepants/src/opty/examples/pendulum_swing_up.py", line 69, in <module>
    solution, info = prob.solve(initial_guess)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cyipopt/cython/ipopt_wrapper.pyx", line 642, in ipopt_wrapper.Problem.solve
  File "cyipopt/cython/ipopt_wrapper.pyx", line 700, in ipopt_wrapper.gradient_cb
  File "/home/moorepants/src/opty/opty/direct_collocation.py", line 228, in gradient
    return self.obj_grad(free)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/moorepants/src/opty/opty/utils.py", line 326, in obj_grad
    *obj_grad_time_expr_eval(states, inputs, free[r_idx:]),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<lambdifygenerated-2>", line 16, in _lambdifygenerated
NameError: name 'Derivative' is not defined
```

**Comment by moorepants** [comment]
This is because Abs isn't continuously differentiable.
