### ISSUE TITLE
Problem with version 1.3.0.dev0

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#172]
When I run the program attached below with opty version 1.2.0 all runs fine.
If I try to run it with opty version 1.3.0.dev0 I get this error:

```
import sympy.physics.mechanics as me
from collections import OrderedDict
import time
import opty
import numpy as np
import sympy as sm
from scipy.optimize import fsolve
from opty.direct_collocation import Problem
#from opty.utils import parse_free
#import matplotlib.pyplot as plt
#import matplotlib
#from IPython.display import HTML
#matplotlib.rcParams['animation.embed_limit'] = 2**128
#from matplotlib.animation import FuncAnimation

print('Sympy version:', sm.__version__)
print('Opty version:', opty.__version__)
print('Numpy version:', np.__version__)
print(f'\n')
#------------------------------------------------------------------------------------------------------------------
# This creates the objective function and its gradient for the direct collocation problem.
#------------------------------------------------------------------------------------------------------------------
def create_objective_function(
    objective, state_symbols, input_symbols, unknown_symbols,
    N, node_time_interval=1.0, integration_method="backward euler"):
    """Creates function to evaluate the objective and objective gradient.

    Parameters
    ----------
    objective : sympy.Expr
        The objective function to be minimized, which is a function of the
        states and inputs. The objective function can contain non-nested
        indefinite integrals of time, e.g. ``Integral(f(t)**2, t)``.
    state_symbols : iterable of symbols
        The state variables.
    input_symbols : iterable of symbols
        The input variables.
    unknown_symbols : iterable of symbols
        The unknown parameters.
    N : int
        Number of collocation nodes, i.e. the number of time steps.
    node_time_interval : float
        The value of the time interval. The default is 1.0, as this term only
        appears in the objective function as a scaling factor.
    integration_method : str, optional
        The method used to integrate the system. The default is "backward
        euler".

    """
    def lambdify_function(expr, multiplication_array, take_sum):
        if take_sum:
            def integration_function(x):
                return node_time_interval * np.sum(x * multiplication_array)
        else:
            def integration_function(x):
                return node_time_interval * x * multiplication_array
        return sm.lambdify(
            (states, inputs, params), expr,
            modules=[{int_placeholder.name: integration_function}, "numpy"],
            cse=True)

    def parse_expr(expr, in_integral=False):
        if not expr.args:
            return expr
        if isinstance(expr, sm.Integral):
            if in_integral:
                raise NotImplementedError("Nested integrals are not supported.")
            if expr.limits != ((me.dynamicsymbols._t,),):
                raise NotImplementedError(
                    "Only indefinite integrals of time are supported.")
            return int_placeholder(parse_expr(expr.function, True))
        return expr.func(*(parse_expr(arg) for arg in expr.args))

    # Parse function arguments
    states = sm.ImmutableMatrix(state_symbols)
    inputs = sm.ImmutableMatrix(sort_sympy(input_symbols))
    params = sm.ImmutableMatrix(sort_sympy(unknown_symbols))
    if states.shape[1] > 1 or inputs.shape[1] > 1 or params.shape[1] > 1:
        raise ValueError(
            'The state, input, and unknown symbols must be column matrices.')
    n, q = states.shape[0], inputs.shape[0]
    i_idx, r_idx = n * N, (n + q) * N

    # Compute analytical gradient of the objective function
    objective_grad = sm.ImmutableMatrix([objective]).jacobian(
        states[:] + inputs[:] + params[:])

    # Replace the integral with a custom function
    int_placeholder = sm.Function("_IntegralFunction")
    objective = parse_expr(objective)
    objective_grad = tuple(parse_expr(objective_grad))

    # Replace zeros with an array of zeros, otherwise lambdify will return a
    # scalar zero instead of an array of zeros.
    objective_grad = tuple(
        np.zeros(N) if grad == 0 else grad for grad in objective_grad[:n + q]
        ) + tuple(objective_grad[n + q:])

    # Define evaluation functions based on the integration method
    if integration_method == "backward euler":
        obj_expr_eval = lambdify_function(
            objective, np.hstack((0, np.ones(N - 1))), True)
        obj_grad_time_expr_eval = lambdify_function(
            objective_grad[:n + q], np.hstack((0, np.ones(N - 1))), False)
        obj_grad_param_expr_eval = lambdify_function(
            objective_grad[n + q:], np.hstack((0, np.ones(N - 1))), True)
        def obj(free):
            states = free[:i_idx].reshape((n, N))
            inputs = free[i_idx:r_idx].reshape((q, N))
            return obj_expr_eval(states, inputs, free[r_idx:])

        def obj_grad(free):
            states = free[:i_idx].reshape((n, N))
            inputs = free[i_idx:r_idx].reshape((q, N))
            return np.hstack((
                *obj_grad_time_expr_eval(states, inputs, free[r_idx:]),
                obj_grad_param_expr_eval(states, inputs, free[r_idx:])
             ))

    elif integration_method == "midpoint":
        obj_expr_eval = lambdify_function(
            objective, np.ones(N - 1), True)
        obj_grad_time_expr_eval = lambdify_function(
            objective_grad[:n + q], np.hstack((0.5, np.ones(N - 2), 0.5)),
            False)
        obj_grad_param_expr_eval = lambdify_function(
            objective_grad[n + q:], np.ones(N - 1), True)
        def obj(free):
            states = free[:i_idx].reshape((n, N))
            states_mid = 0.5 * (states[:, :-1] + states[:, 1:])
            inputs = free[i_idx:r_idx].reshape((q, N))
            inputs_mid = 0.5 * (inputs[:, :-1] + inputs[:, 1:])
            return obj_expr_eval(states_mid, inputs_mid, free[r_idx:])

        def obj_grad(free):
            states = free[:i_idx].reshape((n, N))
            states_mid = 0.5 * (states[:, :-1] + states[:, 1:])
            inputs = free[i_idx:r_idx].reshape((q, N))
            inputs_mid = 0.5 * (inputs[:, :-1] + inputs[:, 1:])
            return np.hstack((
                *obj_grad_time_expr_eval(states, inputs, free[r_idx:]),
                obj_grad_param_expr_eval(states_mid, inputs_mid, free[r_idx:])
            ))

    else:
        raise NotImplementedError(
            f"Integration method '{integration_method}' is not implemented.")

    return obj, obj_grad


def sort_sympy(seq):
    """Returns a sorted list of the symbols."""
    seq = list(seq)
    try:  # symbols
        seq.sort(key=lambda x: x.name)
    except AttributeError:  # functions
        seq.sort(key=lambda x: x.__class__.__name__)
    return seq
#------------------------------------------------------------------------------------------------------------------
# defines the shape of the line the "skateboard" should follow
#------------------------------------------------------------------------------------------------------------------
def strasse(x, a, b):
    return a * (sm.sin(b * x) + sm.cos(3 * b * x))
#------------------------------------------------------------------------------------------------------------------
# set up the EOMs
#------------------------------------------------------------------------------------------------------------------
N, A0, Ab, Af = sm.symbols('N A0 Ab Af', cls= me.ReferenceFrame)
t = me.dynamicsymbols._t
O, Pb, Dmc, Pf = sm.symbols('O Pb Dmc Pf', cls= me.Point)
O.set_vel(N, 0)

q0, qb, qf     = me.dynamicsymbols('q_0 q_b q_f')                                                   # gen. coordinates of the main body, the rear axle, the front axle
u0, ub, uf     = me.dynamicsymbols('u_0 u_b u_f')                                                   # their speeds
x, y           = me.dynamicsymbols('x y')                                                           # coordinates of the point, where the rear axle attaches to the main body
ux, uy         = me.dynamicsymbols('u_x u_y')                                                       # their speeds
Tb, Tf, Fb, Ff = me.dynamicsymbols('T_b T_f F_b F_f')                                               # torque at back wheel, torque at front wheel, forces on Pb, Pf. Control variables

l, m0, mb, mf, iZZ0, iZZb, iZZf = sm.symbols('l m0 mb mf iZZ0, iZZb, iZZf')                         # link length, mass, inertia of skateboard
a, b = sm.symbols('a b')                                                                            # strasse parameters

A0.orient_axis(N, q0, N.z)
A0.set_ang_vel(N, u0 * N.z)
Ab.orient_axis(N, qb, N.z)
Ab.set_ang_vel(N, ub * N.z)
Af.orient_axis(N, qf, N.z)
Af.set_ang_vel(N, uf * N.z)

Pb.set_pos(O, x * N.x + y * N.y)
Pb.set_vel(N, ux * N.x + uy * N.y)

Pf.set_pos(Pb, l * A0.y)   
Pf.v2pt_theory(Pb, N, A0) 

Dmc.set_pos(Pb, l/2 * A0.y)
Dmc.v2pt_theory(Pb, N, A0)

constr_Dmc    = me.dot(Dmc.pos_from(O), N.y) - strasse(me.dot(Dmc.pos_from(O), N.x), a, b)              # Dmc must always be on the strasse
constr_Dmc_dt = constr_Dmc.diff(t)                                                                      # resulting speed constraint.

# Create the skateboard body
I0 = me.inertia(A0, 0, 0, iZZ0)
body0 = me.RigidBody('body0', Dmc, A0, m0, (I0, Dmc))
Ib = me.inertia(Ab, 0, 0, iZZb)
bodyb = me.RigidBody('bodyb', Pb, Ab, mb, (Ib, Pb))
If = me.inertia(Af, 0, 0, iZZf)
bodyf = me.RigidBody('bodyf', Pf, Af, mf, (If, Pf))
BODY = [body0, bodyb, bodyf]


# Forces
FL = [(Pb, Fb * Ab.y), (Pf, Ff * Af.y), (Ab, Tb * N.z), (Af, Tf * N.z)]

kd = sm.Matrix([ux - x.diff(t), uy - y.diff(t), u0 - q0.diff(t), ub - qb.diff(t), uf - qf.diff(t)])    # kinematic differential equations
speed_constr = sm.Matrix([constr_Dmc_dt])                                                                         # speed constraints
hol_constr = sm.Matrix([constr_Dmc])                                                                   # holonomic constraints: Dmc must always be on the strasse

q_ind = [qf, q0, qb, x]
q_dep = [y]
u_ind = [uf, u0, ub,ux]
u_dep = [uy]

# Create the KanesMethod object
KM = me.KanesMethod(
                    N, q_ind=q_ind, u_ind=u_ind, 
                    kd_eqs=kd, 
                    q_dependent=q_dep, 
                    u_dependent=u_dep, 
                    configuration_constraints=hol_constr, 
                    velocity_constraints=speed_constr,
                    )
(fr, frstar) = KM.kanes_equations(BODY, FL)
EOM = kd.col_join(fr + frstar) 
EOM = EOM.col_join(hol_constr)
#------------------------------------------------------------------------------------------------------------------
# set up the direct collocation problem
#------------------------------------------------------------------------------------------------------------------
state_symbols     = tuple((x, y, q0, qb, qf, ux, uy, u0, ub, uf))
laenge            = len(state_symbols)
constant_symbols  = (a, b, l, m0, mb, mf, iZZ0, iZZb, iZZf)
specified_symbols = (Fb, Ff, Tb, Tf)
unknown_symbols   = []

#======================================================================================================
methode = 'backward euler'  # The integration method to use. backward euler or midpoint are the choices
#======================================================================================================

duration  = 7.5                                             # The duration of the simulation.
num_nodes =  300                                            # The number of nodes to use in the direct collocation problem.
t0, tf    = 0.0, duration                                   # The initial and final times

initial_guess = np.ones((len(state_symbols) + len(specified_symbols)) * num_nodes) * 0.01


interval_value = duration / (num_nodes - 1)

# Specify the known system parameters.
par_map = OrderedDict()
par_map[m0]       = 1.0                                      # Mass of the block
par_map[mb]       = 0.1                                      # Mass of the back wheel
par_map[mf]       = 0.1                                      # Mass of the front wheel
par_map[iZZ0]     = 1.                                       # Inertia of the block
par_map[iZZb]     = 0.1                                      # Inertia of the back wheel
par_map[iZZf]     = 0.1                                      # Inertia of the front wheel
par_map[l]        = 3.0                                      # Length of the skateboard
par_map[a]        = 1.                                       # Parameter of the street
par_map[b]        = 0.025                                    # Parameter of the street   

x1                = 0.0                                      # Initial x position of Pb
q01               = -0.3                                     # Initial angle of the block                               

# Calculate the initial value of y, so that the configuration constraint is satisfied.
# as the initial speeds are always zero, the resulting speed constraint is always satisfied
constr_Dmc_lam = sm.lambdify((y, x, q0, a, b, l), constr_Dmc, cse=True)
def hol_func(x0, *args):
    return constr_Dmc_lam(x0, *args)
y0 = 1.                                                   # initial guess for the fsolve for y1
args = (x1, q01, par_map[a], par_map[b], par_map[l])
y1 = fsolve(hol_func, y0, args)

# Specify the objective function and it's gradient.
objective = sm.Integral(1. * (Fb**2 + Ff**2 + Tb**2 + Tf**2), t)
obj, obj_grad = create_objective_function(
    objective, 
    state_symbols, 
    specified_symbols, 
    unknown_symbols,
    num_nodes, 
    interval_value, 
    methode)


initial_state_constraints = {
                            x: x1,
                            y: y1[0],
                            q0: q01,
                            qb: 0.,
                            qf: np.pi/2.,
                            ux: 0.,
                            uy: 0.,
                            u0: 0.,
                            ub: 0.,
                            uf: 0.,
                            }


final_state_constraints    = {
                             x: 12.,
                             ux: 0.,
                             }    
    
instance_constraints = tuple(xi.subs({t: t0}) - xi_val for xi, xi_val in initial_state_constraints.items()) + tuple(xi.subs({t: tf}) - xi_val for xi, xi_val in final_state_constraints.items())

prob = Problem(obj, obj_grad, EOM, state_symbols, num_nodes, interval_value,
        known_parameter_map=par_map,
        instance_constraints=instance_constraints,
        integration_method=methode)

prob.add_option('max_iter', 3000)           # default is 3000
# Find the optimal solution.
solution, info = prob.solve(initial_guess)
print(f'\n')
print('message from optimizer:', info['status_msg'])
print('Iterations needed',len(prob.obj_value))
print(f"objective value {info['obj_val']:.3e}, \n")
``

**Comment by moorepants** [comment]
This runs without error on Linux, so maybe it is something unique to Windows.

**Comment by moorepants** [comment]
@Peter230655 thanks for the well formatted issue. It makes it very easy to copy and paste and test myself.

**Comment by Peter230655** [comment]
> This runs without error on Linux, so maybe it is something unique to Windows.

I recall that this happened once before with some issue: it was fine on Linus, but did not work on windows.
Should I close the issue?

**Comment by Peter230655** [comment]
> @Peter230655 thanks for the well formatted issue. It makes it very easy to copy and paste and test myself.

Now I know that this is the preferred way to  attach a program. It is easy to do, I will do so in future.

**Comment by moorepants** [comment]
>  Should I close the issue?

No, we need to fix it. There should be no errors on Linux, OSX, and Windows.

**Comment by moorepants** [comment]
I see in a Windows CI build that the STDERR does not display:

```
FAILED opty/tests/test_direct_collocation.py::test_pendulum - ImportError: Unable to import the compiled Cython module ufuncify_matrix_0, compilation likely failed. STDERR output from compilation:
C:\Miniconda\envs\test\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\RUNNER~1\AppData\Local\Temp\tmp0v5j2fw2.opty_ufuncify_compile\ufuncify_matrix_0.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
```

**Comment by moorepants** [comment]
May be relevant: https://stackoverflow.com/questions/53279764/python-unicodedecodeerror-how-to-correctly-read-unicode-strings-from-subproces

**Comment by moorepants** [comment]
Also probably related. Looks like you may be able to detect the encoding and pass it to `run()`.

https://github.com/python/cpython/issues/105312

**Comment by Peter230655** [comment]
I am afraid, this is all WAY above my comprehension level! :-(

**Comment by moorepants** [comment]
@Peter230655 do you have an umlaut in the file path? This:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 419: invalid start byte
```

code `0x94` is from an umlaut.

Also, can you type this into python and report the result:

```python
import locale
locale.getencoding()
```

Also type this:

```python
import subprocess
subprocess.run("echo ö", shell=True, text=True, stdout=subprocess.PIPE).stdout.strip("\n")
```

**Comment by Peter230655** [comment]
> @Peter230655 do you have an umlaut in the file path? This:
> 
> 
> 
> ```
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 419: invalid start byte
> 
> ```
> 
> 
> 
> code `0x94` is from an umlaut.
> 
> 
> 
> Also, can you type this into python and report the result:
> 
> 
> 
> ```python
> 
> import locale
> 
> locale.getencoding()
> 
> ```
> 
> 
> 
> Also type this:
> 
> 
> 
> ```python
> 
> import subprocess
> 
> subprocess.run("echo ö", shell=True, text=True, stdout=subprocess.PIPE).stdout.strip("\n")
> 
> ```

I try hard to avoid Umlaute, but it may have slipped in.
When you say file path, what exactly would this be?

I will do as you suggested this afternoon, when I return from work.
Thanks!

**Comment by Peter230655** [comment]
running this:
import locale
locale.getencoding()

gives this output:
'cp1252'

**Comment by Peter230655** [comment]
```
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[5], line 2
      1 import subprocess
----> 2 subprocess.run("echo ö", shell=True, text=True, stdout=subprocess.PIPE).stdout.strip("\n")

File c:\Users\Peter\anaconda3\envs\math\Lib\subprocess.py:550, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    548 with Popen(*popenargs, **kwargs) as process:
    549     try:
--> 550         stdout, stderr = process.communicate(input, timeout=timeout)
    551     except TimeoutExpired as exc:
    552         process.kill()

File c:\Users\Peter\anaconda3\envs\math\Lib\subprocess.py:1196, in Popen.communicate(self, input, timeout)
   1194     self._stdin_write(input)
   1195 elif self.stdout:
-> 1196     stdout = self.stdout.read()
   1197     self.stdout.close()
   1198 elif self.stderr:


Running this:

import subprocess

subprocess.run("echo ö", shell=True, text=True, stdout=subprocess.PIPE).stdout.strip("\n")

gives this output:

File <frozen codecs>:322, in decode(self, input, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start Byte
```

**Comment by moorepants** [comment]
I just merged https://github.com/csu-hmc/opty/pull/174, can you see if that fixes the issue for you.

**Comment by Peter230655** [comment]
TImo told me to get the development version into my environment like this:
pip install git+https://github.com/csu-hmc/opty.git

I suppose, I now have to uninstall the 'old' opy-dev version and then install the #174 version with the line above.
If correct, how would I uninstall, if not correct, what else do I have to do?
Thanks!

**Comment by moorepants** [comment]
You can do:

```
 pip install -U git+https://github.com/csu-hmc/opty.git
```

the `-U` is for "upgrade".

**Comment by Peter230655** [comment]
I did as you told me, but unfortunately the messagw still comes:

```
⎢           -ω(t) + ──(θ(t))           ⎥
⎢                   dt                 ⎥
⎢                                      ⎥
⎢ 2   d                                ⎥
⎢d ⋅m⋅──(ω(t)) + d⋅g⋅m⋅sin(θ(t)) - T(t)⎥
⎣     dt                               ⎦
Exception in thread Thread-10 (_readerthread):
Traceback (most recent call last):
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Peter\anaconda3\envs\math\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 419: invalid start byte
Exception in thread Thread-12 (_readerthread):
Traceback (most recent call last):
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Peter\anaconda3\envs\math\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 419: invalid start byte
b'Algorithm terminated successfully at a locally optimal point, satisfying the convergence tolerances (can be specified by options).'
23.01610921679525
```

**Comment by Peter230655** [comment]
This is the screen shot from Anaconda when I did what you said. Looks normal to me?
![image](https://github.com/csu-hmc/opty/assets/83544146/b36f7777-137c-4a3e-9656-736a6be37315)

**Comment by Peter230655** [comment]
Dumb question: I can play around with it, should get results, and just ignore the message?

**Comment by moorepants** [comment]
It seems you installed it correctly and it seems my fix didn't fix it for you. I'm not sure how to solve this.  I can catch the `UnicodeDecodeError` and just print that the compilation failed. The only option to get the output then is to manually compile the files. This is a difficult bug, as explained in https://github.com/python/cpython/issues/105312.

**Comment by moorepants** [comment]
> Dumb question: I can play around with it, should get results, and just ignore the message?

Yes, it shouldn't affect anything.

**Comment by Peter230655** [comment]
> > Dumb question: I can play around with it, should get results, and just ignore the message?
> 
> Yes, it shouldn't affect anything.

Good! I will start doing this.
Thanks!

**Comment by Peter230655** [comment]
> It seems you installed it correctly and it seems my fix didn't fix it for you. I'm not sure how to solve this. I can catch the `UnicodeDecodeError` and just print that the compilation failed. The only option to get the output then is to manually compile the files. This is a difficult bug, as explained in [python/cpython#105312](https://github.com/python/cpython/issues/105312).

WAY above my head! They could have written this in Chinese, too, my comprehension would be the same.

**Comment by moorepants** [comment]
Hi Peter, please try the latest master branch version and see if that happens to work without an error.

**Comment by Peter230655** [comment]
I will do this afternoon as soon as I get back from work.
I will load it the same way with the -U as you told me earlier?

**Comment by moorepants** [comment]
Yes, `pip install -U git+https://github.com/csu-hmc/opty.git` will update the package to the latest.

**Comment by Peter230655** [comment]
Unfortunately, still there is the error:

```
Exception in thread Thread-5 (_readerthread):
Traceback (most recent call last):
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Peter\anaconda3\envs\math\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 419: invalid start byte
Exception in thread Thread-7 (_readerthread):
Traceback (most recent call last):
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Peter\anaconda3\envs\math\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 419: invalid start byte
```

**Comment by moorepants** [comment]
Do:

```
pip uninstall opty
pip install -U git+https://github.com/csu-hmc/opty.git
```

just in case. I tried to catch the UnicodeDecodeError, so odd that shows up.

**Comment by Peter230655** [comment]
This did the trick!! 
No more message!

**Comment by moorepants** [comment]
If you change a symbol in your program to `I_{x}` instead of `I` for example, I'm curious if then you see the compile error.

**Comment by Peter230655** [comment]
even sympy does not seem to allow a symbol like this: IZZ1_{x}, it raises an error.
Some other symbol I can try?

**Comment by moorepants** [comment]
`Ix = symbols('I_{x}')` not `I_{x} = symbols()`.

**Comment by tjstienstra** [comment]
Won't `I_{x}` give a compile error because of the usage of `{`?

**Comment by moorepants** [comment]
Yes, I want to see if Peter sees the compile error.

**Comment by Peter230655** [comment]
I got the error already in the cell where I set up Kane'd equations:
IZZ1_{x} = sm.symbols('IZZ1_{x}') 
was not accepted

**Comment by moorepants** [comment]
No, actually not. That is not what I mean. You are simply getting a Python syntax error.

`Ix = symbols('I_{x}')` not `I_{x} = symbols()`.

**Comment by Peter230655** [comment]
Now I did it right (reading seems to be a problem for me!) and I got the error below:
```
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)
File c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\opty\utils.py:701, in ufuncify_matrix(args, expr, const, tmp_dir, parallel, show_compile_output)
    700 try:
--> 701     cython_module = importlib.import_module(d['file_prefix'])
    702 except ImportError as error:

File c:\Users\Peter\anaconda3\envs\math\Lib\importlib\__init__.py:126, in import_module(name, package)
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1204, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1176, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1140, in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'ufuncify_matrix_8'

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
Cell In[17], line 2
      1 # Create an optimization problem.
----> 2 prob = Problem(obj, 
      3                obj_grad, 
      4                EOM, 
      5                state_symbols, 
      6                num_nodes, 
      7                interval_value,
      8                known_parameter_map=par_map,
      9                instance_constraints=instance_constraints,
     10                time_symbol=t,
     11                bounds=bounds)
     13 # Use a random positive initial guess.
     14 np.random.seed(12342)

File c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\opty\direct_collocation.py:53, in _DocInherit.get_with_inst.<locals>.f(*args, **kwargs)
     51 @wraps(self.mthd, assigned=('__name__', '__module__'))
     52 def f(*args, **kwargs):
---> 53     return self.mthd(obj, *args, **kwargs)

File c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\opty\direct_collocation.py:161, in Problem.__init__(self, obj, obj_grad, equations_of_motion, state_symbols, num_collocation_nodes, node_time_interval, known_parameter_map, known_trajectory_map, instance_constraints, time_symbol, tmp_dir, integration_method, parallel, bounds, show_compile_output)
    159 self.obj = obj
    160 self.obj_grad = obj_grad
--> 161 self.con = self.collocator.generate_constraint_function()
    162 logging.info('Constraint function generated.')
    163 self.con_jac = self.collocator.generate_jacobian_function()

File c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\opty\direct_collocation.py:1582, in ConstraintCollocator.generate_constraint_function(self)
   1579 """Returns a function which evaluates the constraints given the
   1580 array of free optimization variables."""
   1581 logging.info('Generating constraint function.')
-> 1582 self._gen_multi_arg_con_func()
   1583 return self._wrap_constraint_funcs(self._multi_arg_con_func, 'con')

File c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\opty\direct_collocation.py:1031, in ConstraintCollocator._gen_multi_arg_con_func(self)
   1028     adjacent_stop = None
   1030 logging.info('Compiling the constraint function.')
-> 1031 f = ufuncify_matrix(args, self.discrete_eom,
   1032                     const=constant_syms + (h_sym,),
   1033                     tmp_dir=self.tmp_dir, parallel=self.parallel,
   1034                     show_compile_output=self.show_compile_output)
   1036 def constraints(state_values, specified_values, constant_values,
   1037                 interval_value):
   1038     """Returns a vector of constraint values given all of the
   1039     unknowns in the equations of motion over the 2, ..., N time
   1040     steps.
   (...)
   1059 
   1060     """

File c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\opty\utils.py:706, in ufuncify_matrix(args, expr, const, tmp_dir, parallel, show_compile_output)
    702     except ImportError as error:
    703         msg = ('Unable to import the compiled Cython module {}, '
    704                'compilation likely failed. STDERR output from '
    705                'compilation:\n{}')
--> 706         raise ImportError(msg.format(d['file_prefix'], stderr)) from error
    707 finally:
    708     module_counter += 1

ImportError: Unable to import the compiled Cython module ufuncify_matrix_8, compilation likely failed. STDERR output from compilation:
c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\Peter\AppData\Local\Temp\tmp7ului939.opty_ufuncify_compile\ufuncify_matrix_8.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
                     double q3p,
                     double u1p,
                     double u2p,
                     double u3p,
                     double Fi,
                     double l_{x},
                              ^
------------------------------------------------------------

ufuncify_matrix_8.pyx:21:30: Expected ')', found '{'
Traceback (most recent call last):
  File "C:\Users\Peter\AppData\Local\Temp\tmp7ului939.opty_ufuncify_compile\ufuncify_matrix_8_setup.py", line 14, in <module>
    ext_modules=cythonize([extension]))
                ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "c:\Users\Peter\anaconda3\envs\math\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ufuncify_matrix_8.pyx
```

**Comment by moorepants** [comment]
Perfect! I works. Closing this issue.

Thanks for the troubleshooting.

**Comment by Peter230655** [comment]
My pleasure!
Maybe not so good for you: Now I will likely bug you with questions about the variable h! :-)
