### ISSUE TITLE
park2004 example is erroring with latest versions of dependencies

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/opty#45]
```
moorepants@hanuman:park2004(master)$ python park2004.py 
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
/home/moorepants/miniconda/lib/python2.7/site-packages/pydy/codegen/code.py:25: PyDyDeprecationWarning: This module, 'pydy.codgen.code', is deprecated. The function 'generate_ode_function' can be found in the 'pydy.codegen.ode_function_generator' module. 'CythonGenerator' has been removed, use 'pydy.codegen.cython_code.CythonMatrixGenerator' instead.
  PyDyDeprecationWarning)
Generating equations of motion.
Generating right hand side function.
/home/moorepants/miniconda/lib/python2.7/site-packages/pydy/codegen/code.py:71: PyDyDeprecationWarning: This function is deprecated and will be removed in PyDy 0.4.0. Use the the new 'generate_ode_function' in 'pydy.codegen.ode_function_generator'
  PyDyDeprecationWarning)
Integrating equations of motion.
/home/moorepants/miniconda/lib/python2.7/site-packages/pydy/codegen/ode_function_generators.py:398: PyDyDeprecationWarning: The old style args, i.e. {'constants': , 'specified'}, for the generated function will be removed in PyDy 0.4.0.
  PyDyDeprecationWarning)
/home/moorepants/miniconda/lib/python2.7/site-packages/pydy/codegen/ode_function_generators.py:420: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self._constants_values[i] = p[c]
^C^CTraceback (most recent call last):
  File "park2004.py", line 39, in <module>
    x = odeint(rhs, x0, time, args=(args,))
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/scipy/integrate/odepack.py", line 215, in odeint
    ixpr, mxstep, mxhnil, mxordn, mxords)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/pydy/codegen/ode_function_generators.py", line 543, in rhs
    args = self._parse_all_args(*args)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/pydy/codegen/ode_function_generators.py", line 481, in _parse_all_args
    args = self._parse_specifieds(*args)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/pydy/codegen/ode_function_generators.py", line 463, in _parse_specifieds
    self._specifieds_values[:] = r(x, t)
  File "/home/moorepants/src/opty/examples/park2004/model.py", line 558, in controller
    result = interp_func(t)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/scipy/interpolate/polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 586, in _evaluate
    y_new = self._call(self, x_new)
  File "/home/moorepants/miniconda/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 557, in _call_linear
    y_new = slope*(x_new - x_lo)[:, None] + y_lo
KeyboardInterrupt
```

**Comment by moorepants** [comment]
The above only happens in Python 3.

Also fix depwarnings:

```
/home/moorepants/miniconda3/envs/opty-py2/lib/python2.7/site-packages/pydy/codegen/code.py:25: PyDyDeprecationWarning: This module, 'pydy.codgen.code', is deprecated. The function 'generate_ode_function' can be found in the 'pydy.codegen.ode_function_generator' module. 'CythonGenerator' has been removed, use 'pydy.codegen.cython_code.CythonMatrixGenerator' instead.
  PyDyDeprecationWarning)
```
