### ISSUE TITLE
Invalid C variables are possible

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/opty#47]
I used `i` as a state variable and opty creates `ii` and `in` in the C code. `in` is an invalid variable name in C, so the compilation fails. I think SymPy deals with this properly now with the CCode printers, but maybe this one slipped through.

```
(pendulum-robot) moorepants@garuda:cython_files$ python ufuncify_matrix_0_setup.py build_ext --inplace
Compiling ufuncify_matrix_0.pyx because it changed.
[1/1] Cythonizing ufuncify_matrix_0.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    void eval_matrix(double matrix[3], double thetai,
                 double omegai,
                 double ii,
                 double thetan,
                 double omegan,
                 double in,
                       ^
------------------------------------------------------------

ufuncify_matrix_0.pyx:11:24: Expected ')', found 'in'
Traceback (most recent call last):
  File "ufuncify_matrix_0_setup.py", line 13, in <module>
    ext_modules=cythonize([extension]))
  File "/home/moorepants/miniconda3/envs/pendulum-robot/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 934, in cythonize
    cythonize_one(*args)
  File "/home/moorepants/miniconda3/envs/pendulum-robot/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1056, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: ufuncify_matrix_0.pyx
```

**Comment by moorepants** [comment]
These are the reserved words we look for in SymPy:

```python
reserved_words = [
    'auto', 'break', 'case', 'char', 'const', 'continue', 'default', 'do',
    'double', 'else', 'enum', 'extern', 'float', 'for', 'goto', 'if', 'int',
    'long', 'register', 'return', 'short', 'signed', 'sizeof', 'static',
    'struct', 'entry',  # never standardized, we'll leave it here anyway
    'switch', 'typedef', 'union', 'unsigned', 'void', 'volatile', 'while'
]
```

which does not include "in".
